export default {
  UPDATE_GUEST_PASTE: "UPDATE_GUEST_PASTE",
  UPDATE_GUEST_SYNTAX: "UPDATE_GUEST_SYNTAX",
  CREATE_PASTE: "CREATE_PASTE",
  CREATE_PASTE_SUCCESS: "CREATE_PASTE_SUCCESS",
  CREATE_PASTE_FAIL: "CREATE_PASTE_FAIL",
  SET_STATUS_TO_GUEST: "SET_STATUS_TO_GUEST",
  FETCH_PASTE: "FETCH_PASTE",
  FETCH_PASTE_SUCCESS: "FETCH_PASTE_SUCCESS",
  FETCH_PASTE_FAIL: "FETCH_PASTE_FAIL",
  FORK_PASTE_START: "FORK_PASTE_START",
  FORK_PASTE: "FORK_PASTE"
};
